name: flutter_keychain
description: Flutter secure storage via Keychain and Keystore
version: 2.7.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.appmire.flutterkeychain
        pluginClass: FlutterKeychainPlugin
      ios:
        pluginClass: FlutterKeychainPlugin
